// export const homeObjOne = {
//   id:'about',
//   lightBg: false,
//   lightText: true,
//   lightTextDesc: true,
//   topLine: 'About Me',
//   headline: 'Full-Stack Software Engineer with a background in Sound for Film and TV',
//   description: 'Something about me asflkjhdsafdp ahjfdsh ajhfdsfudaip fa ahljkdhfguisdag nfkljdhfuilyt hajkfhldauiaiudag dskjghsdlkguyhdsug anjasklhgadiul lhafjd kaj fiasdjfids fjka hjfiadshf iu afkjahdf',
//   buttonLabel: 'Contact Me',
//   imgStart: false,
//   img: require('../../images/me.svg'),
//   alt: 'me',
//   dark: true,
//   primary: true,
//   darkText: false,
// }